include(CheckIPOSupported)

check_ipo_supported(RESULT ALFRED_IPO_SUPPORTED OUTPUT ALFRED_IPO_ERROR_MESSAGE LANGUAGES CXX)

if(NOT ALFRED_IPO_SUPPORTED)
    message(WARNING ${ALFRED_IPO_ERROR_MESSAGE})
endif()
