set(SDL_SHARED OFF)
set(SDL_STATIC ON)
set(SDL_TEST_LIBRARY OFF)

set(SDL_X11_XSCRNSAVER OFF)
set(SDL_X11_XTEST OFF)

add_subdirectory(extern/SDL)

set(SDL_INCLUDE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/extern/SDL/include")
